import { UserProfileService } from '@core/services';
import { SalonListDto } from '@features/intranet/pages/admin/horarios/models/salon.interface';
import {
	ActualizarUsuarioRequest,
	CrearUsuarioRequest,
	ROLES_USUARIOS_ADMIN,
	RolUsuarioAdmin,
} from '../../services';
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { generatePassword } from '@core/helpers';
import { rolRequiereSalon, rolPermiteEsTutor, canEditPassword, esSeccionDeVerano } from '@shared/models';
import { APP_USER_ROLES } from '@shared/constants';

import { ButtonModule } from 'primeng/button';
import { Checkbox } from 'primeng/checkbox';
import { CommonModule } from '@angular/common';
import { DatePickerModule } from 'primeng/datepicker';
import { DialogModule } from 'primeng/dialog';
import { FormFieldErrorComponent } from '@shared/components';
import { FormsModule } from '@angular/forms';
import { InputTextModule } from 'primeng/inputtext';
import { PasswordModule } from 'primeng/password';
import { SelectModule } from 'primeng/select';
import { TableModule } from 'primeng/table';
import { ToggleSwitch } from 'primeng/toggleswitch';
import { UppercaseInputDirective } from '@shared/directives';
import { EstadoLabelPipe } from '@shared/pipes';

export type UsuarioFormData = Partial<CrearUsuarioRequest & ActualizarUsuarioRequest>;

export interface FormValidationErrors {
	dniError: string | null;
	correoError: string | null;
	correoApoderadoError: string | null;
	nombreApoderadoError: string | null;
	telefonoApoderadoError: string | null;
}

/**
 * Componente presentacional para el dialog de formulario de usuario
 * Edición y creación de usuarios
 */
@Component({
	selector: 'app-usuario-form-dialog',
	standalone: true,
	imports: [
		CommonModule,
		FormsModule,
		DialogModule,
		ButtonModule,
		InputTextModule,
		SelectModule,
		ToggleSwitch,
		PasswordModule,
		DatePickerModule,
		FormFieldErrorComponent,
		TableModule,
		UppercaseInputDirective,
		Checkbox,
		EstadoLabelPipe,
	],
	templateUrl: './usuario-form-dialog.component.html',
	styleUrl: './usuario-form-dialog.component.scss',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UsuarioFormDialogComponent {
	// #region Dependencias
	private userProfile = inject(UserProfileService);
	// #endregion

	// #region Inputs / Outputs
	readonly visible = input.required<boolean>();
	readonly isEditing = input.required<boolean>();
	readonly formData = input.required<UsuarioFormData>();
	readonly errors = input.required<FormValidationErrors>();
	readonly isFormValid = input.required<boolean>();
	readonly loading = input<boolean>(false);
	readonly salones = input<SalonListDto[]>([]);

	readonly visibleChange = output<boolean>();
	readonly fieldChange = output<{ field: string; value: unknown }>();
	readonly save = output<void>();
	readonly cancelDialog = output<void>();
	// #endregion

	// #region Estado local
	readonly rolesSelectOptions = ROLES_USUARIOS_ADMIN.map((r) => ({ label: r, value: r }));

	// Selector de salón en dos pasos: primero grado, luego sección
	readonly _gradoSeleccionado = signal<string | null>(null);
	readonly _seccionSeleccionada = signal<string | null>(null);

	readonly canEditPassword = computed(() => canEditPassword(this.userProfile.userRole()));
	// #endregion

	// #region Computed — validaciones de contraseña

	/**
	 * Obtiene la contraseña actual del formulario
	 */
	private readonly _contrasena = computed(() => {
		const pwd = this.formData().contrasena;
		return typeof pwd === 'string' ? pwd : '';
	});

	/**
	 * Valida longitud mínima de 8 caracteres
	 */
	readonly contrasenaMinLengthValid = computed(() => {
		const pwd = this._contrasena();
		return pwd.length >= 8;
	});

	/**
	 * Valida al menos una mayúscula
	 */
	readonly contrasenaHasUppercase = computed(() => {
		const pwd = this._contrasena();
		return /[A-Z]/.test(pwd);
	});

	/**
	 * Valida al menos una minúscula
	 */
	readonly contrasenaHasLowercase = computed(() => {
		const pwd = this._contrasena();
		return /[a-z]/.test(pwd);
	});

	/**
	 * Valida al menos un número
	 */
	readonly contrasenaHasNumber = computed(() => {
		const pwd = this._contrasena();
		return /[0-9]/.test(pwd);
	});

	/**
	 * Valida al menos un carácter especial
	 */
	readonly contrasenaHasSpecialChar = computed(() => {
		const pwd = this._contrasena();
		return /[!@#$%^&*(),.?":{}|<>]/.test(pwd);
	});

	/**
	 * Indica si todas las validaciones de contraseña son válidas
	 */
	readonly contrasenaValidationsValid = computed(() => {
		const pwd = this._contrasena();
		// Si no hay contraseña, no hay error (puede ser opcional según el contexto)
		if (!pwd) return true;

		return (
			this.contrasenaMinLengthValid() &&
			this.contrasenaHasUppercase() &&
			this.contrasenaHasLowercase() &&
			this.contrasenaHasNumber() &&
			this.contrasenaHasSpecialChar()
		);
	});

	autoGeneratedValue = computed(() => {
		// En edición, usar la contraseña real del backend
		if (this.isEditing()) {
			return this.formData().contrasena ?? '';
		}

		// En creación, auto-generar desde apellido + DNI
		return generatePassword(this.formData().apellidos ?? '', this.formData().dni ?? '');
	});
	// #endregion

	// #region Computed — opciones de salón
	readonly isEstudiante = computed(() => this.formData().rol === APP_USER_ROLES.Estudiante);
	readonly isProfesor = computed(() => rolPermiteEsTutor(this.formData().rol));
	readonly needsSalon = computed(() => rolRequiereSalon(this.formData().rol));

	// Helper para tipar correctamente el rol
	get rolValue(): RolUsuarioAdmin | undefined {
		return this.formData().rol as RolUsuarioAdmin | undefined;
	}

	private formatSeccion(seccion: string): string {
		return esSeccionDeVerano(seccion) ? 'Verano' : seccion;
	}

	readonly gradosOptions = computed(() => {
		const salones = this.salones();
		const gradosUnicos = new Set<string>();
		const result: { label: string; value: string }[] = [];

		salones.forEach((s) => {
			if (!gradosUnicos.has(s.grado)) {
				gradosUnicos.add(s.grado);
				result.push({ label: s.grado, value: s.grado });
			}
		});

		return result;
	});

	readonly seccionesOptions = computed(() => {
		const grado = this._gradoSeleccionado();
		if (!grado) return [];

		const salones = this.salones();
		const seccionesDelGrado = salones
			.filter((s) => s.grado === grado)
			.map((s) => ({
				label: this.formatSeccion(s.seccion),
				value: s.seccion,
			}));

		return seccionesDelGrado;
	});

	readonly salonSeleccionado = computed(() => {
		const grado = this._gradoSeleccionado();
		const seccion = this._seccionSeleccionada();
		if (!grado || !seccion) return null;

		const salones = this.salones();
		return salones.find((s) => s.grado === grado && s.seccion === seccion) || null;
	});
	// #endregion

	// #region Event handlers
	onVisibleChange(visible: boolean): void {
		this.visibleChange.emit(visible);
	}

	onFieldChange(field: string, value: unknown): void {
		this.fieldChange.emit({ field, value });
	}

	onGradoChange(grado: string | null): void {
		this._gradoSeleccionado.set(grado);
		this._seccionSeleccionada.set(null);
		this.fieldChange.emit({ field: 'salonId', value: undefined });
		this.fieldChange.emit({ field: 'grado', value: undefined });
		this.fieldChange.emit({ field: 'seccion', value: undefined });
	}

	onSeccionChange(seccion: string | null): void {
		this._seccionSeleccionada.set(seccion);
		const salon = this.salonSeleccionado();
		if (salon) {
			this.fieldChange.emit({ field: 'salonId', value: salon.salonId });
			this.fieldChange.emit({ field: 'grado', value: salon.grado });
			this.fieldChange.emit({ field: 'seccion', value: salon.seccion });
		} else {
			this.fieldChange.emit({ field: 'salonId', value: undefined });
			this.fieldChange.emit({ field: 'grado', value: undefined });
			this.fieldChange.emit({ field: 'seccion', value: undefined });
		}
	}

	// Sync grado/sección local cuando cambia formData.salonId (al abrir edición)
	private readonly _syncGradoSeccion = effect(() => {
		const formData = this.formData();
		const salonId = formData.salonId;
		const salones = this.salones();

		if (salonId && salones.length > 0) {
			const salon = salones.find((s) => s.salonId === salonId);
			if (salon) {
				this._gradoSeleccionado.set(salon.grado);
				this._seccionSeleccionada.set(salon.seccion);

				// Sync grado/seccion to store if they differ (e.g., student has salonId but EST_Grado/EST_Seccion are null)
				if (formData.grado !== salon.grado) {
					this.fieldChange.emit({ field: 'grado', value: salon.grado });
				}
				if (formData.seccion !== salon.seccion) {
					this.fieldChange.emit({ field: 'seccion', value: salon.seccion });
				}
			}
		} else if (formData.grado) {
			// Initialize local signals from formData when no salonId
			this._gradoSeleccionado.set(formData.grado ?? null);
			this._seccionSeleccionada.set(formData.seccion ?? null);
		}
	});

	onSave(): void {
		this.save.emit();
	}

	onCancel(): void {
		this.cancelDialog.emit();
	}
	// #endregion
}
