import {
	ActualizarUsuarioRequest,
	CrearUsuarioRequest,
	ROLES_USUARIOS_ADMIN,
	RolUsuarioAdmin,
	UserProfileService,
} from '@core/services';
import { ChangeDetectionStrategy, Component, computed, inject, input, output } from '@angular/core';

import { ButtonModule } from 'primeng/button';
import { CommonModule } from '@angular/common';
import { DatePickerModule } from 'primeng/datepicker';
import { DialogModule } from 'primeng/dialog';
import { FormFieldErrorComponent } from '@shared/components';
import { FormsModule } from '@angular/forms';
import { InputTextModule } from 'primeng/inputtext';
import { PasswordModule } from 'primeng/password';
import { SelectModule } from 'primeng/select';
import { TableModule } from 'primeng/table';
import { ToggleSwitch } from 'primeng/toggleswitch';
import { UppercaseInputDirective } from '@shared/directives';

export type UsuarioFormData = Partial<CrearUsuarioRequest & ActualizarUsuarioRequest>;

export interface FormValidationErrors {
	dniError: string | null;
	correoError: string | null;
	correoApoderadoError: string | null;
}

/**
 * Componente presentacional para el dialog de formulario de usuario
 * Edición y creación de usuarios
 */
@Component({
	selector: 'app-usuario-form-dialog',
	standalone: true,
	imports: [
		CommonModule,
		FormsModule,
		DialogModule,
		ButtonModule,
		InputTextModule,
		SelectModule,
		ToggleSwitch,
		PasswordModule,
		DatePickerModule,
		FormFieldErrorComponent,
		TableModule,
		UppercaseInputDirective,
	],
	templateUrl: './usuario-form-dialog.component.html',
	styleUrl: './usuario-form-dialog.component.scss',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UsuarioFormDialogComponent {
	private userProfile = inject(UserProfileService);

	readonly visible = input.required<boolean>();
	readonly isEditing = input.required<boolean>();
	readonly formData = input.required<UsuarioFormData>();
	readonly errors = input.required<FormValidationErrors>();
	readonly isFormValid = input.required<boolean>();

	readonly visibleChange = output<boolean>();
	readonly fieldChange = output<{ field: string; value: unknown }>();
	readonly save = output<void>();
	readonly cancelDialog = output<void>();

	readonly rolesSelectOptions = ROLES_USUARIOS_ADMIN.map((r) => ({ label: r, value: r }));

	readonly allowEditPasswordRoles = ['Director', 'Asistente Administrativo'];

	// Computed - Solo Director puede editar contraseñas
	readonly canEditPassword = computed(() =>
		this.allowEditPasswordRoles.includes(this.userProfile.userRole()),
	);
	autoGeneratedValue = computed(() => {
		const apellido = (this.formData().apellidos ?? '').trim();
		const dniRaw = (this.formData().dni ?? '').trim();

		// 2 primeras letras del primer apellido en mayúsculas
		const pref = apellido.slice(0, 2).toUpperCase();

		// Solo dígitos del DNI y últimos 4
		const digits = dniRaw.replace(/\D/g, '');
		const suf = digits.slice(-4);

		// Regla: si falta algo, devuelve vacío (o podrías devolver '—')
		if (pref.length < 2 || suf.length < 4) return '';

		return `${pref}${suf}`;
	});

	// Computed - Es estudiante si rol es Estudiante
	get isEstudiante(): boolean {
		return this.formData().rol === 'Estudiante';
	}

	// Helper para tipar correctamente el rol
	get rolValue(): RolUsuarioAdmin | undefined {
		return this.formData().rol as RolUsuarioAdmin | undefined;
	}

	onVisibleChange(visible: boolean): void {
		this.visibleChange.emit(visible);
	}

	onFieldChange(field: string, value: unknown): void {
		this.fieldChange.emit({ field, value });
	}

	onSave(): void {
		this.save.emit();
	}

	onCancel(): void {
		this.cancelDialog.emit();
	}
}
