import { PresetEndpoint } from './ctest-k6.models';

// #region Preset Endpoints
export const PRESET_ENDPOINTS: PresetEndpoint[] = [
	{
		category: 'General (todos los roles)',
		endpoints: [
			{
				enabled: true,
				method: 'GET',
				path: '/api/sistema/permisos/mis-permisos',
				body: '',
				name: 'mis-permisos',
			},
			{
				enabled: true,
				method: 'GET',
				path: '/api/horario/mi-horario-hoy',
				body: '',
				name: 'mi-horario-hoy',
			},
			{
				enabled: true,
				method: 'GET',
				path: '/api/ServerTime',
				body: '',
				name: 'server-time',
			},
		],
	},
	{
		category: 'Estudiante — sin parámetros',
		endpoints: [
			{
				enabled: true,
				method: 'GET',
				path: '/api/EstudianteCurso/mis-horarios',
				body: '',
				name: 'estudiante-mis-horarios',
			},
			{
				enabled: true,
				method: 'GET',
				path: '/api/EstudianteCurso/mis-notas',
				body: '',
				name: 'estudiante-mis-notas',
			},
			{
				enabled: true,
				method: 'GET',
				path: '/api/consultaasistencia/estudiante/mis-asistencias?mes=3&anio=2026',
				body: '',
				name: 'estudiante-mis-asistencias',
			},
		],
	},
	{
		category: 'Estudiante — con ID (cambiar IDs según BD)',
		endpoints: [
			{
				enabled: false,
				method: 'GET',
				path: '/api/EstudianteCurso/horario/6/contenido',
				body: '',
				name: 'estudiante-contenido-horario',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/EstudianteCurso/semana/17/mis-archivos',
				body: '',
				name: 'estudiante-mis-archivos-semana',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/EstudianteCurso/tarea/3/mis-archivos',
				body: '',
				name: 'estudiante-mis-tarea-archivos',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/EstudianteCurso/horario/6/mi-asistencia',
				body: '',
				name: 'estudiante-mi-asistencia-curso',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/EstudianteCurso/horario/6/grupos',
				body: '',
				name: 'estudiante-grupos-horario',
			},
		],
	},
	{
		category: 'Profesor — sin parámetros',
		endpoints: [
			{
				enabled: true,
				method: 'GET',
				path: '/api/Profesor/mis-estudiantes',
				body: '',
				name: 'profesor-mis-estudiantes',
			},
			{
				enabled: true,
				method: 'GET',
				path: '/api/consultaasistencia/profesor/salones',
				body: '',
				name: 'profesor-salones',
			},
			{
				enabled: true,
				method: 'GET',
				path: '/api/consultaasistencia/profesor/salones-horario',
				body: '',
				name: 'profesor-salones-horario',
			},
		],
	},
	{
		category: 'Profesor — con ID (cambiar IDs según BD)',
		endpoints: [
			{
				enabled: false,
				method: 'GET',
				path: '/api/Horario/profesor/13',
				body: '',
				name: 'profesor-horarios',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/ProfesorSalon/profesor/13',
				body: '',
				name: 'profesor-salon-tutoria',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/Profesor/estudiantes-salon/12',
				body: '',
				name: 'profesor-estudiantes-salon',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/CursoContenido/horario/5',
				body: '',
				name: 'profesor-contenido-horario',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/CursoContenido/2/archivos-estudiantes',
				body: '',
				name: 'profesor-archivos-estudiantes',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/CursoContenido/tarea/3/archivos-estudiantes',
				body: '',
				name: 'profesor-archivos-tarea-estudiantes',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/Calificacion/contenido/2',
				body: '',
				name: 'profesor-calificaciones',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/Calificacion/periodos/2',
				body: '',
				name: 'profesor-periodos',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/Calificacion/salon/12/curso/10',
				body: '',
				name: 'profesor-notas-salon',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/GrupoContenido/contenido/3',
				body: '',
				name: 'profesor-grupos-contenido',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/AsistenciaCurso/horario/5/fecha?fecha=2026-03-07',
				body: '',
				name: 'profesor-asistencia-curso-fecha',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/AsistenciaCurso/horario/5/resumen?fechaInicio=2026-03-01&fechaFin=2026-03-07',
				body: '',
				name: 'profesor-asistencia-curso-resumen',
			},
		],
	},
	{
		category: 'Profesor — Mensajería (cambiar IDs según BD)',
		endpoints: [
			{
				enabled: false,
				method: 'GET',
				path: '/api/conversaciones/listar?horarioId=5',
				body: '',
				name: 'profesor-conversaciones',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/conversaciones/6',
				body: '',
				name: 'profesor-conversacion-detalle',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/conversaciones/destinatarios',
				body: '',
				name: 'profesor-destinatarios',
			},
		],
	},
	{
		category: 'Admin (Director)',
		endpoints: [
			{
				enabled: false,
				method: 'GET',
				path: '/api/sistema/usuarios/listar',
				body: '',
				name: 'listar-usuarios',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/sistema/salones/listar',
				body: '',
				name: 'listar-salones',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/sistema/cursos/listar',
				body: '',
				name: 'listar-cursos',
			},
			{
				enabled: false,
				method: 'GET',
				path: '/api/consultaasistencia/director/estadisticas?fecha=2026-03-07',
				body: '',
				name: 'director-estadisticas-asistencia',
			},
		],
	},
];
// #endregion
