import type { SeasonalNotification } from './notifications.types';
import { isWithinMonthDays, isMonth } from './notifications-date.utils';

export const EVENTO_NOTIFICATIONS: SeasonalNotification[] = [
	// Inicio de clases
	{
		id: 'inicio-clases-evento',
		type: 'evento',
		title: 'Inicio de Clases',
		message: 'Comienza un nuevo ano escolar. Bienvenidos a todos los estudiantes.',
		icon: 'pi-book',
		priority: 'high',
		shouldShow: (date) => isMonth(date, 3) && isWithinMonthDays(date, 1, 3),
		actionUrl: '/intranet/calendario',
		actionText: 'Ver calendario',
		dismissible: true,
	},
	// Reunion de padres inicial
	{
		id: 'reunion-padres-inicial',
		type: 'evento',
		title: 'Reunion General de Padres',
		message: 'Primera reunion del ano escolar. Se presentara el plan curricular.',
		icon: 'pi-users',
		priority: 'high',
		shouldShow: (date) => isMonth(date, 3) && isWithinMonthDays(date, 14, 16),
		actionUrl: '/intranet/calendario',
		actionText: 'Ver calendario',
		dismissible: true,
	},
	// Dia del libro
	{
		id: 'dia-libro',
		type: 'evento',
		title: 'Dia Mundial del Libro',
		message: 'Celebracion del Dia del Libro. Actividades de lectura e intercambio.',
		icon: 'pi-book',
		priority: 'medium',
		shouldShow: (date) => isMonth(date, 4) && isWithinMonthDays(date, 19, 23),
		actionUrl: '/intranet/calendario',
		actionText: 'Ver actividades',
		dismissible: true,
	},
	{
		id: 'reunion-padres-1',
		type: 'evento',
		title: 'Reunion de Padres - Primer Bimestre',
		message: 'Proxima reunion de padres de familia. Revisa la fecha en el calendario.',
		icon: 'pi-users',
		priority: 'high',
		shouldShow: (date) => isMonth(date, 4) && isWithinMonthDays(date, 20, 25),
		actionUrl: '/intranet/calendario#today',
		actionText: 'Ver calendario',
		dismissible: true,
	},
	// Examenes parciales
	{
		id: 'examenes-parciales',
		type: 'evento',
		title: 'Periodo de Examenes Parciales',
		message: 'Inicio del periodo de evaluaciones parciales. Revisa el cronograma.',
		icon: 'pi-file-edit',
		priority: 'high',
		shouldShow: (date) => isMonth(date, 5) && isWithinMonthDays(date, 13, 17),
		actionUrl: '/intranet/calendario',
		actionText: 'Ver cronograma',
		dismissible: true,
	},
	// Dia de la bandera
	{
		id: 'dia-bandera',
		type: 'evento',
		title: 'Dia de la Bandera',
		message: 'Ceremonia civica en honor al Dia de la Bandera. Desfile escolar.',
		icon: 'pi-flag',
		priority: 'medium',
		shouldShow: (date) => isMonth(date, 6) && isWithinMonthDays(date, 6, 7),
		actionUrl: '/intranet/calendario',
		actionText: 'Ver detalles',
		dismissible: true,
	},
	{
		id: 'reunion-padres-2',
		type: 'evento',
		title: 'Reunion de Padres - Segundo Bimestre',
		message: 'Proxima reunion de padres de familia. Revisa la fecha en el calendario.',
		icon: 'pi-users',
		priority: 'high',
		shouldShow: (date) => isMonth(date, 7) && isWithinMonthDays(date, 10, 15),
		actionUrl: '/intranet/calendario#today',
		actionText: 'Ver calendario',
		dismissible: true,
	},
	// Olimpiadas deportivas
	{
		id: 'olimpiadas-deportivas',
		type: 'evento',
		title: 'Olimpiadas Deportivas',
		message: 'Inicio de las olimpiadas deportivas interescolares.',
		icon: 'pi-trophy',
		priority: 'medium',
		shouldShow: (date) => isMonth(date, 8) && isWithinMonthDays(date, 14, 16),
		actionUrl: '/intranet/calendario',
		actionText: 'Ver programacion',
		dismissible: true,
	},
	{
		id: 'reunion-padres-3',
		type: 'evento',
		title: 'Reunion de Padres - Tercer Bimestre',
		message: 'Proxima reunion de padres de familia. Revisa la fecha en el calendario.',
		icon: 'pi-users',
		priority: 'high',
		shouldShow: (date) => isMonth(date, 9) && isWithinMonthDays(date, 20, 25),
		actionUrl: '/intranet/calendario#today',
		actionText: 'Ver calendario',
		dismissible: true,
	},
	{
		id: 'aniversario-colegio',
		type: 'evento',
		title: 'Aniversario del Colegio',
		message: 'Celebremos juntos el aniversario de nuestra institucion.',
		icon: 'pi-star',
		priority: 'medium',
		// Adjust this date for the real anniversary.
		shouldShow: (date) => isMonth(date, 5) && isWithinMonthDays(date, 15, 17),
		dismissible: true,
	},
	// Examenes finales
	{
		id: 'examenes-finales',
		type: 'evento',
		title: 'Periodo de Examenes Finales',
		message: 'Inicio del periodo de evaluaciones finales. Prepararse con anticipacion.',
		icon: 'pi-file-edit',
		priority: 'high',
		shouldShow: (date) => isMonth(date, 11) && isWithinMonthDays(date, 13, 17),
		actionUrl: '/intranet/calendario',
		actionText: 'Ver cronograma',
		dismissible: true,
	},
	{
		id: 'clausura',
		type: 'evento',
		title: 'Ceremonia de Clausura',
		message: 'Se acerca la ceremonia de clausura del ano escolar. No faltes.',
		icon: 'pi-star-fill',
		priority: 'high',
		shouldShow: (date) => isMonth(date, 12) && isWithinMonthDays(date, 12, 18),
		actionUrl: '/intranet/calendario#today',
		actionText: 'Ver detalles',
		dismissible: true,
	},
];

