export {
	CalificacionConfigService,
	clasificarNota,
	getNotaSeverity,
	getGradeClass,
	isNotaAprobada,
	convertToLiteral,
	formatNotaConConfig,
	UMBRAL_COBERTURA_PROMEDIO_GENERAL,
	calcularPorcentajeEvaluado,
	esPromedioProvisional,
	clasificarPromedioConCobertura,
	getPromedioSeverity,
	type NotaClasificacion,
} from './calificacion-config.service';
