// Auto-generated by: npm run gen:caps
// Source: GET /api/admin/capabilities/roles/catalog
// Do not edit manually — regenerate with: npm run gen:caps

export type CapabilityCode =
	| 'ADMIN_AUDITORIA_CORREOS'
	| 'ADMIN_CAMPUS'
	| 'ADMIN_EMAIL_ALERTS'
	| 'ADMIN_EMAIL_BLACKLIST'
	| 'ADMIN_EMAIL_DEFER_EVENTS'
	| 'ADMIN_EMAIL_OUTBOX'
	| 'ADMIN_EMAIL_OUTBOX_DIAGNOSTICO'
	| 'ADMIN_EMAIL_QUARANTINE'
	| 'ADMIN_ERROR_LOGS'
	| 'ADMIN_EVENTOS_CALENDARIO'
	| 'ADMIN_MONITOREO'
	| 'ADMIN_NOTIFICACIONES'
	| 'ADMIN_PERMISOS_ROLES'
	| 'ADMIN_PERMISOS_USUARIOS'
	| 'ADMIN_RATE_LIMIT_EVENTS'
	// F10-w1b (2026-09-09): sin contraparte en el BE actual (ni enum ni las 27 filas de seed
	// confirmadas de Catálogo B) — se limpia solo con la próxima corrida real de `npm run gen:caps`.
	| 'ADMIN_REGISTRO_VISTAS'
	| 'ADMIN_REPORTES_USUARIO'
	| 'ADMIN_SISTEMA_DB_DIAGNOSTICS'
	| 'ADMIN_SISTEMA_RUNTIME_HEALTH'
	| 'ADMIN_USUARIOS'
	| 'ASISTENCIA'
	| 'ASISTENCIA_ADMIN'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_ASISTENCIAS`.
	| 'ASISTENCIA_ADMIN_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ESTUDIANTE_ASISTENCIA`.
	| 'ASISTENCIA_ESTUDIANTE_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `PROFESOR_ASISTENCIA`.
	| 'ASISTENCIA_PROFESOR_PAGE_VIEW'
	| 'AYUDA_MANAGE'
	| 'AYUDA_TICKET_MANAGE'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `CALENDARIO`.
	| 'CALENDARIO_PAGE_USE'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ESTUDIANTE_NOTAS`.
	| 'CALIFICACIONES_ESTUDIANTE_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `PROFESOR_CALIFICACIONES`.
	| 'CALIFICACIONES_PROFESOR_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_CURSOS`.
	| 'CURSOS_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `PROFESOR_CURSOS`.
	| 'CURSOS_PROFESOR_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_EMAIL_DOMAIN_PAUSES`.
	| 'EMAIL_DOMINIO_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_EMAIL_OUTBOX_DASHBOARD_DIA`.
	| 'EMAIL_OUTBOX_DASHBOARD_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_EMAIL_RECIPIENT_VIEW`. Esa fila nunca
	// había aparecido en este tipo generado (drift: seedeada en BE pero sin ítem de menú/uso en FE
	// hasta hoy, y `gen:caps` nunca corrió después de agregarla) — se agrega recién con su nombre nuevo.
	| 'EMAIL_RECIPIENT_PAGE_VIEW'
	| 'ESTUDIANTE_CURSOS'
	| 'EXPLICACIONES_MANAGE'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ESTUDIANTE_FORO`.
	| 'FORO_ESTUDIANTE_PAGE_USE'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `PROFESOR_FORO`.
	| 'FORO_PROFESOR_PAGE_USE'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `CTEST_K6`.
	| 'HERRAMIENTAS_TEST_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ESTUDIANTE_HORARIOS`.
	| 'HORARIOS_ESTUDIANTE_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_HORARIOS`.
	| 'HORARIOS_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `PROFESOR_HORARIOS`.
	| 'HORARIOS_PROFESOR_PAGE_VIEW'
	| 'INTRANET'
	// Manually appended (brief 559, Plan 101 F4) — `JUSTIFICACION_ASISTENCIA_APROBAR`
	// fue seedeada en `Educa.API` (migración manual
	// `20260813_CreateSolicitudJustificacionAsistenciaTable.sql`, brief 557) pero
	// `npm run gen:caps` necesita una sesión autenticada que no puede enviar en este
	// entorno. Mismo caso que `AYUDA_MANAGE` arriba.
	// Remover este comentario cuando un regen naturalmente la incluya.
	| 'JUSTIFICACION_ASISTENCIA_APROBAR'
	| 'MENSAJERIA'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ESTUDIANTE_MENSAJERIA`.
	| 'MENSAJERIA_ESTUDIANTE_PAGE_USE'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `PROFESOR_MENSAJERIA`.
	| 'MENSAJERIA_PROFESOR_PAGE_USE'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_PERMISOS_SALUD`.
	| 'PERMISOS_SALUD_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_RENDIMIENTO` (agregada a la tabla del
	// plan recién en esta wave — no estaba en el listado original de 26, ver plan §Catálogo B).
	// Sigue sin regen real de `gen:caps` por el mismo motivo que `AYUDA_MANAGE` arriba.
	| 'RENDIMIENTO_ADMIN_PAGE_VIEW'
	// Manually appended (brief 489) — `REPORTES_RENDIMIENTO` fue seedeada en
	// `Educa.API` (briefs 490/489) pero `npm run gen:caps` necesita una sesión
	// autenticada que no puede enviar en este entorno. Mismo caso que
	// `AYUDA_MANAGE`/`AYUDA_TICKET_MANAGE` arriba. Remover este comentario
	// cuando un regen naturalmente la incluya.
	| 'REPORTES_RENDIMIENTO'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ESTUDIANTE_SALONES`.
	| 'SALONES_ESTUDIANTE_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `ADMIN_SALONES`.
	| 'SALONES_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `PROFESOR_FINAL_SALONES`.
	| 'SALONES_PROFESOR_FINAL_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `PROFESOR_SALONES`.
	| 'SALONES_PROFESOR_PAGE_VIEW'
	// F10-w1b (2026-09-09) — rename de Catálogo B, ex `VIDEOCONFERENCIAS`.
	| 'VIDEOCONFERENCIAS_PAGE_USE';
