// Auto-generated by: npm run gen:caps
// Source: GET /api/admin/capabilities/roles/catalog
// Do not edit manually — regenerate with: npm run gen:caps

export type CapabilityCode =
	| 'ADMIN_ASISTENCIAS'
	| 'ADMIN_AUDITORIA_CORREOS'
	| 'ADMIN_CAMPUS'
	| 'ADMIN_CURSOS'
	| 'ADMIN_EMAIL_ALERTS'
	| 'ADMIN_EMAIL_BLACKLIST'
	| 'ADMIN_EMAIL_DEFER_EVENTS'
	| 'ADMIN_EMAIL_DOMAIN_PAUSES'
	| 'ADMIN_EMAIL_OUTBOX'
	| 'ADMIN_EMAIL_OUTBOX_DASHBOARD_DIA'
	| 'ADMIN_EMAIL_OUTBOX_DIAGNOSTICO'
	| 'ADMIN_EMAIL_QUARANTINE'
	| 'ADMIN_ERROR_LOGS'
	| 'ADMIN_EVENTOS_CALENDARIO'
	| 'ADMIN_HORARIOS'
	| 'ADMIN_MONITOREO'
	| 'ADMIN_NOTIFICACIONES'
	| 'ADMIN_PERMISOS_ROLES'
	| 'ADMIN_PERMISOS_SALUD'
	| 'ADMIN_PERMISOS_USUARIOS'
	| 'ADMIN_RATE_LIMIT_EVENTS'
	| 'ADMIN_REGISTRO_VISTAS'
	| 'ADMIN_REPORTES_USUARIO'
	| 'ADMIN_SALONES'
	| 'ADMIN_SISTEMA_DB_DIAGNOSTICS'
	| 'ADMIN_SISTEMA_RUNTIME_HEALTH'
	| 'ADMIN_USUARIOS'
	| 'ASISTENCIA'
	| 'ASISTENCIA_ADMIN'
	// Manually appended (briefs 483/484) — both `AYUDA_MANAGE` and
	// `AYUDA_TICKET_MANAGE` are seeded in `Educa.API` migrations but
	// `npm run gen:caps` needs an authenticated session it can't send, so
	// these were added by hand. Remove this comment once a regen naturally
	// includes both.
	| 'AYUDA_MANAGE'
	| 'AYUDA_TICKET_MANAGE'
	| 'CALENDARIO'
	| 'CTEST_K6'
	| 'ESTUDIANTE_ASISTENCIA'
	| 'ESTUDIANTE_CURSOS'
	| 'ESTUDIANTE_FORO'
	| 'ESTUDIANTE_HORARIOS'
	| 'ESTUDIANTE_MENSAJERIA'
	| 'ESTUDIANTE_NOTAS'
	| 'ESTUDIANTE_SALONES'
	| 'INTRANET'
	| 'MENSAJERIA'
	| 'PROFESOR_ASISTENCIA'
	| 'PROFESOR_CALIFICACIONES'
	| 'PROFESOR_CURSOS'
	| 'PROFESOR_FINAL_SALONES'
	| 'PROFESOR_FORO'
	| 'PROFESOR_HORARIOS'
	| 'PROFESOR_MENSAJERIA'
	| 'PROFESOR_SALONES'
	// Manually appended (brief 489) — `REPORTES_RENDIMIENTO` fue seedeada en
	// `Educa.API` (briefs 490/489) pero `npm run gen:caps` necesita una sesión
	// autenticada que no puede enviar en este entorno. Mismo caso que
	// `AYUDA_MANAGE`/`AYUDA_TICKET_MANAGE` arriba. Remover este comentario
	// cuando un regen naturalmente la incluya.
	| 'REPORTES_RENDIMIENTO'
	| 'VIDEOCONFERENCIAS';
